services:
  database:
    container_name: database
    image: ${DOCKERHUB_USERNAME}/tp-devops-database:latest
    env_file:
      - ./simpleapi/.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app-blue:
    container_name: app-blue
    image: ${DOCKERHUB_USERNAME}/tp-devops-simple-api:latest
    env_file:
      - ./simpleapi/.env
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  app-green:
    container_name: app-green
    image: ${DOCKERHUB_USERNAME}/tp-devops-simple-api:latest
    env_file:
      - ./simpleapi/.env
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  front:
    container_name: front
    image: ${DOCKERHUB_USERNAME}/tp-devops-front:latest
    networks:
      - app-network
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: ${DOCKERHUB_USERNAME}/tp-devops-httpd:latest
    env_file:
      - ./simpleapi/.env
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - front
      - app-blue
      - app-green
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
