name: CD devops 2025

on:
  workflow_run:
    workflows:
      - CI devops 2025
    branches:
      - main
    types:
      - completed

jobs:
  build-and-push-backend:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest" ./TP1/simpleapi
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest"

  build-and-push-database:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push database
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest" ./TP1/database
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest"

  build-and-push-httpd:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push httpd
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest" ./TP1/httpd
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest"
